### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Dadibom** [gdaws/node-stomp#101]
Sending and receiving lots of messages causes this:

```
RangeError: Maximum call stack size exceeded
    at Frame.removeListener (events.js:329:28)
    at cleanup (_stream_readable.js:701:10)
    at Frame.onunpipe (_stream_readable.js:685:9)
    at Frame.emit (events.js:210:5)
    at BufferReadable.Readable.unpipe (_stream_readable.js:831:12)
    at unpipe (_stream_readable.js:780:9)
    at Frame.onerror (_stream_readable.js:756:5)
    at Frame.emit (events.js:215:7)
    at service (node_modules/stompit/lib/OutgoingFrameStream.js:211:19)
    at dequeue (node_modules/stompit/lib/OutgoingFrameStream.js:263:3)
```

**Comment by Dadibom** [comment]
Might be an easy fix to just use setTimeout(service/dequeue, 0) instead of calling them recursively
