### ISSUE TITLE
Recursive process.nextTick detected. This will break in the next version of node.

### ISSUE THREAD

**Issue by choudhary001** [gdaws/node-stomp#43]
I am using node v0.10.36 and got below warning when I tried to use client.ack(message) method:

node.js:402
        throw new Error(msg);
              ^
Error: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
    at maxTickWarn (node.js:402:15)
    at process._nextTick [as _currentTickHandler] (node.js:507:9)
    at process.nextTick (node.js:358:15)
    at onwrite (_stream_writable.js:266:15)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at Socket._write (net.js:654:5)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Socket.Writable.write (_stream_writable.js:183:11)
    at Socket.write (net.js:616:40)
    at service (/u/choudhab/node_modules/stompit/lib/OutgoingFrameStream.js:245:28)
    at dequeue (/u/choudhab/node_modules/stompit/lib/OutgoingFrameStream.js:263:3)

**Comment by gdaws** [comment]
To fix warning, upgrade your node installation to latest version or to at least version 0.11.10

It's safe to ignore the warning message if upgrading node is not possible.

For details on what causes the warning message, see issue #29.
