### ISSUE TITLE
client.ack is not a function

### ISSUE THREAD

**Issue by davidkirwan** [gdaws/node-stomp#44]
Hi there,

I'm getting the following error when running the example code for node-stomp https://github.com/gdaws/node-stomp/blob/master/README.md 

    TypeError: client.ack is not a function
        at /home/david/tmp/node_stomp/app.js:50:14
        at IncomingFrame.<anonymous> (/home/david/tmp/node_stomp/node_modules/stompit/lib/IncomingFrameStream.js:488:5)
        at emitNone (events.js:72:20)
        at IncomingFrame.emit (events.js:166:7)
        at endReadableNT (_stream_readable.js:913:12)
        at nextTickCallbackWith2Args (node.js:442:9)
        at process._tickCallback (node.js:356:17)

nodejs version 4.4.3
stompit version 0.22.0

Looking at the API it seems the ack() is something which should be called on the message rather than the client, and changing from client.ack(message) to message.ack(); resolved the issue. Might be a case of documentation/code desync.

**Comment by gdaws** [comment]
Yeah it's a case of documentation/code desync. The documentation in README.md in the master branch isn't compatible with the API in version 0.22.0.

The client.ack function is introduced in version 0.23.0
