### ISSUE TITLE
Cannot connect with path

### ISSUE THREAD

**Issue by gioragutt** [gdaws/node-stomp#74]
Hi! I'm trying to connect with stompit with the following connection variables (passed as first parameter to `stompit.connect`):
```javascript
const connectOptions = {
  host: activeMqHost,
  port: activeMqPort,
  connectHeaders: {
    login: activeMqUsername,
    passcode: activeMqPassword,
  },
}
```
and
`const connectOptions = 'localhost' // or 'localhost:61613' or 'stomp://localhost:61613', or even a connection string from AmazonMQ (which has a stomp endpoint).

I get the following error back:

```javascript
{
  "code": "ENOENT",
  "errno": "ENOENT",
  "syscall": "connect",
  "address": "localhost",
  "connectArgs": {
    "host": "localhost",
    "port": 61613,
    "timeout": 3000,
    "connectHeaders": {},
    "path": "localhost"
  }
}
```

Also, when I use a connection string with a different port, f.e: `localhost:61614`

```javascript
{
  "code": "ENOENT",
  "errno": "ENOENT",
  "syscall": "connect",
  "address": "localhost:6164",
  "connectArgs": {
    "host": "localhost",
    "port": 61613,
    "timeout": 3000,
    "connectHeaders": {},
    "path": "localhost:6164"
  }
}
```

Of course, the stack is:

```bash
Error: failed to connect to active mq  
at stompit.connect (D:\\WD\\pocs\\stox-amq\\src\\lib\\server.js:64:18)
at Client.onError (D:\\WD\\pocs\\stox-amq\\node_modules\\stompit\\lib\\connect.js:48:7)
at emitOne (events.js:115:13)
at Client.emit (events.js:210:7)
at Client.Socket.destroy (D:\\WD\\pocs\\stox-amq\\node_modules\\stompit\\lib\\Socket.js:136:12)
at Socket.<anonymous> (D:\\WD\\pocs\\stox-amq\\node_modules\\stompit\\lib\\Socket.js:48:10)
at emitOne (events.js:120:20)
at Socket.emit (events.js:210:7)
at emitErrorNT (internal/streams/destroy.js:64:8)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

using `"stompit": "^0.25.0"`

**Comment by gioragutt** [comment]
What if I don't want to use an object? I want the connection string to come from an environment variable, and pass it to the `connect` function.

Also, based on the [api](http://gdaws.github.io/node-stomp/api/connect/), you support path as a parameter.

**Comment by gdaws** [comment]
The path parameter expects a value that references a file path to a UNIX domain socket.

In your application, define a function that parses a connection string into an object acceptable to the connect function.

**Comment by gioragutt** [comment]
Thanks, I did that. Just a quick question tho.

Have you had success connecting to AmazonMQ before? It's basically ActiveMQ, it has a STOMP endpoint, but I can't get the library to connect to it...

**Comment by hanman18** [comment]
Not sure if this is the appropriate place to ask, but Im having an issue connecting to AmazonMQ via STOMP client library. I haven't added any header info. in the connect function. Do you know if this is needed to connect to AmazonMQ?

**Comment by gdaws** [comment]
I had no prior experience with AmazonMQ, but I was able to create a new instance in AWS and extract configuration details.

The STOMP endpoint uses TLS; therefore the settings `ssl: true` and `port: 61614` must be passed in the connect options.

The username and password is passed through the connectHeader options, as login and passcode respectively.

**Comment by rorystandley** [comment]
@hanman18 Did you manage to get connected with AmazonMQ? I just keep getting connection timeout
