### ISSUE TITLE
Processing Error

### ISSUE THREAD

**Issue by kevinmlong** [gdaws/node-stomp#79]
I'm getting the error below thrown, but curious why I'm not seeing it in the callbacks (for both connection and subscription messages) where I check for error. 

```js
if (error) {
        console.log('error occurred: ' + error.message);
        return;
}
```

**ERROR**
```sh
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: Processing error
    at Client.Socket._createError (/home/node/app/node_modules/stompit/lib/Socket.js:258:13)
    at Client.Socket.createApplicationError (/home/node/app/node_modules/stompit/lib/Socket.js:292:20)
    at Client.onError (/home/node/app/node_modules/stompit/lib/Client.js:409:20)
    at readFrameBody (/home/node/app/node_modules/stompit/lib/Socket.js:79:15)
    at readIncomingFrame (/home/node/app/node_modules/stompit/lib/Socket.js:102:5)
    at process._tickCallback (internal/process/next_tick.js:176:11)
Emitted 'error' event at:
    at Client.Socket.destroy (/home/node/app/node_modules/stompit/lib/Socket.js:136:12)
    at IncomingFrame.<anonymous> (/home/node/app/node_modules/stompit/lib/Client.js:420:12)
    at IncomingFrame.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
error An unexpected error occurred: "Command failed.
Exit code: 1
```
Any thoughts?

**Comment by kevinmlong** [comment]
I think this may have had to do with when I was ack-ing a message. Immediately ack-ing a message then processing it, seems to have resolved the issue.
